language: ruby
rvm: 2.5.1
services: postgresql
cache: bundler
env:
    global:
      - secure: "P+3u97p+wxvLS6Ix33hPWa/XPhNOrX8qUs4UNtAMs8a+/8e6W4byfK3Rga6K7cVhOkfaDhPUAvIxAojJ4KKITkPmgc6p/fNm714croYmfMIlDBTcxURWLbGMMxS0qeBv8iqoSYEkORrq4gXsV+xsgS6Zz3Bdtis2IdY5U3RE94A6UvQ4Sq3wBGBa+r8QhOOpbcxaxDzkNWyblUPjyWfXy/TMMkstot++3OIjJsy6tMOF5124VTrsJyaDAIt5yLcVkuVLhnr44fa4vKG/zk2vrzaPJMXwQTR91KQl0O7cpYgYJbjx+Qj7KQm/PDn1vvbrbwbgNhOKRTZ9phnVCB8w+6o6w/x20U6Sk7hS6ny3oGBa2IspSVoTGm1tKngW6P2ifmobJHmNzWskomrH0UJc8lrfi7kXaEZmZ+fTOpaiJGlIx0ivdXLTcS4r/DsQA80Ow5nfQoS36MFGP1gFUcs+2ONqTvzvT9tlKDwPbZyHuR/dGES6n6jXpFJsp0dSPT2MabYd3M7okUcL18Ad75TbU4jwRXsUr9gibHdFVoD5VboTlUBCfKPZdgjRSvLNMPjxa3jRShl55Rau9eAGsbv7czboqn6/e+9l+u1itfPrLIYV7oluw9IWcXk/IHElmhlO2/UkEZabi5wJdsZWaHJMCWwcr4OIIi6bkQos3dRPVyQ="
script: 
  - bundle exec rails test