language: ruby
rvm: 2.5.1
services: postgresql
cache: bundler
branches:
  only:
    - master
    - stable
env:
  global:
    - secure: "P+3u97p+wxvLS6Ix33hPWa/XPhNOrX8qUs4UNtAMs8a+/8e6W4byfK3Rga6K7cVhOkfaDhPUAvIxAojJ4KKITkPmgc6p/fNm714croYmfMIlDBTcxURWLbGMMxS0qeBv8iqoSYEkORrq4gXsV+xsgS6Zz3Bdtis2IdY5U3RE94A6UvQ4Sq3wBGBa+r8QhOOpbcxaxDzkNWyblUPjyWfXy/TMMkstot++3OIjJsy6tMOF5124VTrsJyaDAIt5yLcVkuVLhnr44fa4vKG/zk2vrzaPJMXwQTR91KQl0O7cpYgYJbjx+Qj7KQm/PDn1vvbrbwbgNhOKRTZ9phnVCB8w+6o6w/x20U6Sk7hS6ny3oGBa2IspSVoTGm1tKngW6P2ifmobJHmNzWskomrH0UJc8lrfi7kXaEZmZ+fTOpaiJGlIx0ivdXLTcS4r/DsQA80Ow5nfQoS36MFGP1gFUcs+2ONqTvzvT9tlKDwPbZyHuR/dGES6n6jXpFJsp0dSPT2MabYd3M7okUcL18Ad75TbU4jwRXsUr9gibHdFVoD5VboTlUBCfKPZdgjRSvLNMPjxa3jRShl55Rau9eAGsbv7czboqn6/e+9l+u1itfPrLIYV7oluw9IWcXk/IHElmhlO2/UkEZabi5wJdsZWaHJMCWwcr4OIIi6bkQos3dRPVyQ="
    - CC_TEST_REPORTER_ID=46fd59d90ed03c3e7228237e6dc33bd8079e5d047f38ab99801744573b170c30
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: 
  - bundle exec rails test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT